FROM ubuntu:bionic

RUN apt update && \
    apt install -y g++ cmake git \
			    python python-dev python-pip python-requests && \
    pip install numpy scikit-image tensorflow dlib gunicorn multipart && \
    mkdir /prnet_http_server
