#!/usr/bin/env bash
cd "$(dirname "$0")"
git clone --depth=1 https://github.com/YadiraF/PRNet.git PRNet && \
./download_from_google_drive 1UoE-XuW1SDLUjZmJPkIZ1MLxvQFgmTFH PRNet/Data/net-data/256_256_resfcn256_weight.data-00000-of-00001
touch PRNet/__init__.py
ln -s PRNet/Data
